# Generated by Django 3.2.8 on 2021-10-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True)),
                ('descripcion', models.TextField(max_length=225)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True)),
                ('apellido', models.CharField(max_length=225)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(max_length=225)),
                ('celular', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True)),
                ('apellido', models.CharField(max_length=225)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(max_length=225)),
                ('celular', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True)),
                ('descripcion', models.TextField(max_length=225)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='Jhordamy.categoria')),
                ('proveedor', models.ForeignKey(default='available', on_delete=django.db.models.deletion.CASCADE, to='Jhordamy.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
